package pmedit.ui.preferences;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import pmedit.BatchMan;
import pmedit.Constants;
import pmedit.LicenseHttpClientHelper;
import pmedit.OsCheck;
import pmedit.ext.PmeExtension;
import pmedit.serdes.SerDeslUtils;
import pmedit.ui.components.TextPaneWithLinks;
import pmedit.util.HttpResponseCallback;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Map;
import java.util.prefs.Preferences;

public class LicensePreferences {

    public JPanel topPanel;
    public JTextField licensedTo;
    public JTextField licenseId;
    public JLabel labelLicenseStatus;
    public TextPaneWithLinks header;
    public JTextField expirationDate;
    public JButton acquireOrRelease;


    public LicensePreferences() {
        header.setText("<h3 align='center'>Enter license information below to unlock full functionality.</h3><p align='center'>You can get license at <a href=\"" + Constants.batchLicenseUrl + "\">" + Constants.batchLicenseUrl + "</a></p>");
        acquireOrRelease.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (BatchMan.hasBatch()) {
                    releaseLicense();
                } else {
                    acquireLicense();
                }
            }
        });
    }


    public void init(Preferences prefs) {
        licenseId.setText(prefs.get("licenseId", ""));
        licensedTo.setText(prefs.get("licensedTo", ""));
    }


    public void refresh() {
        pmedit.prefs.Preferences.MotoBoto key = pmedit.prefs.Preferences.getMotoBoto();
        if (key.isEmpty()) {
            labelLicenseStatus.setText("No license");
            expirationDate.setText("n/a");
            acquireOrRelease.setText("Acquire");
            return;
        }
        if (BatchMan.hasBatch()) {
            labelLicenseStatus.setText("Valid license");
            expirationDate.setText(BatchMan.getExpiration().toString());
            acquireOrRelease.setText("Release");

        } else {
            labelLicenseStatus.setText("Invalid license");
            expirationDate.setText("n/a");
            acquireOrRelease.setText("Acquire");

        }
    }

    public void save(Preferences prefs) {
        prefs.put("licenseId", licenseId.getText().trim());
        prefs.put("licensedTo", licensedTo.getText().trim());
    }


    private void acquireLicense() {
        acquireOrRelease.setEnabled(false);
        labelLicenseStatus.setText("Acquiring license...");
        PmeExtension ext = PmeExtension.get();

        ext.giveBatch(licensedTo.getText() + "," + licenseId.getText(),
                new HttpResponseCallback() {
                    @Override
                    public void onSuccess(int statusCode, String responseBody) {
                        refresh();
                        acquireOrRelease.setEnabled(true);
                    }

                    @Override
                    public void onError(String errorMessage) {
                        labelLicenseStatus.setText(errorMessage);
                        acquireOrRelease.setEnabled(true);
                    }
                });

    }

    private void releaseLicense() {
        acquireOrRelease.setEnabled(false);
        labelLicenseStatus.setText("Releasing license...");
        PmeExtension ext = PmeExtension.get();

        ext.removeBatch(
                new HttpResponseCallback() {
                    @Override
                    public void onSuccess(int statusCode, String responseBody) {
                        refresh();
                        acquireOrRelease.setEnabled(true);
                    }

                    @Override
                    public void onError(String errorMessage) {
                        labelLicenseStatus.setText(errorMessage);
                        acquireOrRelease.setEnabled(true);
                    }
                });

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        topPanel = new JPanel();
        topPanel.setLayout(new GridLayoutManager(7, 2, new Insets(10, 10, 10, 10), -1, -1));
        header = new TextPaneWithLinks();
        topPanel.add(header, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("License ID");
        topPanel.add(label1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelLicenseStatus = new JLabel();
        labelLicenseStatus.setText("No License");
        topPanel.add(labelLicenseStatus, new GridConstraints(6, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        topPanel.add(spacer1, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setHorizontalAlignment(4);
        label2.setText("License Email");
        topPanel.add(label2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        licensedTo = new JTextField();
        licensedTo.setEditable(true);
        topPanel.add(licensedTo, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Expiration Date");
        topPanel.add(label3, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        expirationDate = new JTextField();
        expirationDate.setEditable(false);
        topPanel.add(expirationDate, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        licenseId = new JTextField();
        licenseId.setText("");
        topPanel.add(licenseId, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        acquireOrRelease = new JButton();
        acquireOrRelease.setText("Acquire");
        topPanel.add(acquireOrRelease, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topPanel;
    }

}
