package pmedit.ui.preferences;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.nio.client.CloseableHttpAsyncClient;
import org.apache.http.impl.nio.client.HttpAsyncClients;
import org.apache.http.util.EntityUtils;
import pmedit.Constants;
import pmedit.SerDeslUtils;
import pmedit.Version;
import pmedit.ui.components.TextPaneWithLinks;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.util.HashMap;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;

public class AboutPreferences {
    public JPanel topPanel;
    public TextPaneWithLinks aboutText;
    public TextPaneWithLinks checkForUpdatesText;
    Version.VersionTuple latestVersion;
    String checkStatusText;

    public AboutPreferences() {
        aboutText.setText(
                "<h1 align=center>" + Version.getAppName() + "</h1>\n\n" +
                        "<p align=center><a href=\"" + Constants.websiteUrl + "\">" + Constants.websiteUrl + "</a></p>\n<br>\n" +
                        "<p align=center>If you have suggestions, found bugs or just want to share some idea about it you can write me at : <a href=\"" + Constants.contactFormUrl + "\">" + Constants.contactFormUrl + "</a></p>\n<br>"
        );

        checkForUpdatesText.addActionHandler("update-check://", (action) -> {
            (new Thread(new Runnable() {

                @Override
                public void run() {
                    final Future<HttpResponse> status = checkForUpdates();
                    showUpdatesStatus(status);
                }
            })).start();
        });
        refresh();
    }

    public void refresh() {
        checkForUpdatesText.setText(
                getVersionHtml()
        );
    }

    String getVersionHtml() {
        Version.VersionTuple current = Version.get();
        String versionMsg;
        if (checkStatusText != null) {
            versionMsg = "<h3 align=center>" + checkStatusText + "</h3>";
        }
        if (latestVersion != null) {
            if (current.cmp(latestVersion) < 0) {
                versionMsg = "<h3 align=center>New version available: <a href='" + Constants.downloadUrl + "'>"
                        + latestVersion.getAsString() + "</a> , current: " + current.getAsString() + "</h3>";
            } else {
                versionMsg = "<h3 align=center>Version " + current.getAsString() + " is the latest version</h3>";
            }
        } else {
            versionMsg = "<h3 align=center><a href=\"update-check://\">Check for updates</a></h3>";
        }
        return "<h3 align=center>Version: " + current.getAsString() + "</h3><br>" + versionMsg;
    }

    private Future<HttpResponse> checkForUpdates() {
        checkStatusText = "Checking...";
        refresh();
        CloseableHttpAsyncClient httpclient = HttpAsyncClients.createDefault();
        httpclient.start();
        HttpGet request = new HttpGet("https://api.github.com/repos/zaro/pdf-metadata-editor/releases?per_page=1");
        Future<HttpResponse> future = httpclient.execute(request, null);
        return future;
    }

    private void showUpdatesStatus(Future<HttpResponse> status) {
        try {
            HttpResponse response = status.get();
            String lastsVersion = null;
            HttpEntity entity = response.getEntity();

            java.util.List<HashMap<String, Object>> body = SerDeslUtils.listFromJSON(EntityUtils.toString(entity));
            if (!body.isEmpty()) {
                lastsVersion = (String) (body.get(0)).get("name");
            }
            if (lastsVersion != null) {
                latestVersion = new Version.VersionTuple(lastsVersion);
            }
        } catch (InterruptedException | ExecutionException | IOException e1) {
            checkStatusText = e1.toString();
        } finally {
            refresh();
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        topPanel = new JPanel();
        topPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        aboutText = new TextPaneWithLinks();
        topPanel.add(aboutText, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        checkForUpdatesText = new TextPaneWithLinks();
        topPanel.add(checkForUpdatesText, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topPanel;
    }

}
