package pmedit.ui.preferences;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import pmedit.MetadataInfo;
import pmedit.ui.MetadataEditPane;

import javax.swing.*;
import java.awt.*;
import java.util.prefs.Preferences;

public class DefaultsPreferences {
    public JPanel topPanel;
    public MetadataEditPane defaultMetadataPane;
    public MetadataInfo defaultMetadata;

    public DefaultsPreferences() {

    }

    public void init(Preferences prefs) {
        this.defaultMetadata = new MetadataInfo();
        String defaultMetadataYaml = prefs.get("defaultMetadata", "");
        if (!defaultMetadataYaml.isEmpty()) {
            this.defaultMetadata.fromYAML(defaultMetadataYaml);
        }
    }

    public void refresh() {
        defaultMetadataPane.fillFromMetadata(defaultMetadata);
    }

    public void save(Preferences prefs) {
        defaultMetadataPane.copyToMetadata(defaultMetadata);
        prefs.put("defaultMetadata", defaultMetadata.toYAML());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        topPanel = new JPanel();
        topPanel.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        defaultMetadataPane = new MetadataEditPane();
        topPanel.add(defaultMetadataPane.$$$getRootComponent$$$(), new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(5, 5, 5, 5), -1, -1));
        topPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setHorizontalTextPosition(0);
        label1.setText("<html>\nHere you can define default values for fields which are unset in the document.<br>\nThe values are populated on file load.\n</html>");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topPanel;
    }

}
