package pmedit.ui.preferences;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import pmedit.CommandLine;
import pmedit.MetadataInfo;
import pmedit.TemplateString;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.prefs.Preferences;

public class GeneralPreferences {
    public JCheckBox onsaveCopyDocumentTo;
    public JCheckBox onsaveCopyXmpTo;
    public JRadioButton rdbtnSave;
    public JRadioButton rdbtnSaveAndRename;
    public JRadioButton rdbtnSaveAs;
    public JComboBox comboBox;
    public JLabel previewLabel;
    public JTextPane txtpnAaa;
    public JPanel topPanel;

    public boolean copyBasicToXmp;
    public boolean copyXmpToBasic;
    public String defaultSaveAction;
    public String renameTemplate;


    public GeneralPreferences() {
        Preferences prefs = pmedit.prefs.Preferences.getInstance();
        // Copy metadata
        onsaveCopyDocumentTo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                if (onsaveCopyDocumentTo.isSelected()) {
                    onsaveCopyXmpTo.setSelected(false);
                }
                copyBasicToXmp = onsaveCopyDocumentTo.isSelected();
                copyXmpToBasic = onsaveCopyXmpTo.isSelected();
            }
        });
        onsaveCopyXmpTo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                if (onsaveCopyXmpTo.isSelected()) {
                    onsaveCopyDocumentTo.setSelected(false);
                }
                copyBasicToXmp = onsaveCopyDocumentTo.isSelected();
                copyXmpToBasic = onsaveCopyXmpTo.isSelected();
            }
        });
        copyBasicToXmp = prefs.getBoolean("onsaveCopyBasicTo", false);
        copyXmpToBasic = prefs.getBoolean("onsaveCopyXmpTo", false);
        renameTemplate = prefs.get("renameTemplate", null);

        // Default save action
        ActionListener onDefaultSaveAction = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (rdbtnSave.isSelected()) {
                    defaultSaveAction = "save";
                } else if (rdbtnSaveAndRename.isSelected()) {
                    defaultSaveAction = "saveRename";

                } else if (rdbtnSaveAs.isSelected()) {
                    defaultSaveAction = "saveAs";
                }
            }
        };
        rdbtnSave.addActionListener(onDefaultSaveAction);
        rdbtnSaveAndRename.addActionListener(onDefaultSaveAction);
        rdbtnSaveAs.addActionListener(onDefaultSaveAction);
        defaultSaveAction = prefs.get("defaultSaveAction", "save");
        if (defaultSaveAction.equals("saveRename")) {
            rdbtnSaveAndRename.setSelected(true);
        } else if (defaultSaveAction.equals("saveAs")) {
            rdbtnSaveAndRename.setSelected(true);
        } else {
            rdbtnSave.setSelected(true);
        }


        // Rename template
        comboBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                showPreview((String) comboBox.getModel().getSelectedItem());
            }
        });
        comboBox.setModel(new DefaultComboBoxModel(new String[]{"", "{doc.author} - {doc.title}.pdf",
                "{doc.author} - {doc.creationDate}.pdf"}));

        txtpnAaa.setText(
                "Supported fields:<br>\n<pre>\n<i>" + CommandLine.mdFieldsHelpMessage(60, "  {", "}", false) + "</i></pre>");

    }

    public void showPreview(String template) {
        renameTemplate = template;
        TemplateString ts = new TemplateString(template);

        previewLabel.setText("Preview:" + ts.process(MetadataInfo.getSampleMetadata()));
    }

    public void init(Preferences prefs) {
    }

    public void refresh() {
        onsaveCopyDocumentTo.setSelected(copyBasicToXmp);
        onsaveCopyXmpTo.setSelected(copyXmpToBasic);

        comboBox.setSelectedItem(renameTemplate);
        showPreview(renameTemplate);
    }

    public void save(Preferences prefs) {
        prefs.putBoolean("onsaveCopyXmpTo", copyXmpToBasic);
        prefs.putBoolean("onsaveCopyBasicTo", copyBasicToXmp);
        if (renameTemplate != null && !renameTemplate.isEmpty())
            prefs.put("renameTemplate", renameTemplate);
        else
            prefs.remove("renameTemplate");

        prefs.put("defaultSaveAction", defaultSaveAction);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        topPanel = new JPanel();
        topPanel.setLayout(new GridLayoutManager(2, 4, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        topPanel.add(panel1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "On Save ...", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        onsaveCopyDocumentTo = new JCheckBox();
        onsaveCopyDocumentTo.setText("Copy Document to XMP");
        panel1.add(onsaveCopyDocumentTo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        onsaveCopyXmpTo = new JCheckBox();
        onsaveCopyXmpTo.setText("Copy XMP to Document");
        panel1.add(onsaveCopyXmpTo, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        topPanel.add(panel2, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "Default Save Action", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        rdbtnSave = new JRadioButton();
        rdbtnSave.setText("Save");
        panel2.add(rdbtnSave, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel2.add(spacer2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        rdbtnSaveAndRename = new JRadioButton();
        rdbtnSaveAndRename.setText("Save  Rename");
        rdbtnSaveAndRename.setMnemonic(' ');
        rdbtnSaveAndRename.setDisplayedMnemonicIndex(5);
        panel2.add(rdbtnSaveAndRename, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rdbtnSaveAs = new JRadioButton();
        rdbtnSaveAs.setText("Save as ...");
        panel2.add(rdbtnSaveAs, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        topPanel.add(panel3, new GridConstraints(1, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        panel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "Rename template", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final Spacer spacer3 = new Spacer();
        panel3.add(spacer3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        comboBox = new JComboBox();
        panel3.add(comboBox, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        previewLabel = new JLabel();
        previewLabel.setText("Preview:");
        panel3.add(previewLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel3.add(scrollPane1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        txtpnAaa = new JTextPane();
        txtpnAaa.setContentType("text/html");
        scrollPane1.setViewportView(txtpnAaa);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(rdbtnSave);
        buttonGroup.add(rdbtnSaveAndRename);
        buttonGroup.add(rdbtnSaveAs);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topPanel;
    }

}
