package pmedit.ui.preferences;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.apache.pdfbox.pdfwriter.compress.CompressParameters;
import pmedit.FileOptimizer;
import pmedit.MetadataInfo;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.text.DefaultFormatter;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.prefs.Preferences;

public class OptimizationPreferenesPane {
    public JPanel topPanel;
    public JRadioButton noCompresstionRadioButton;
    public JRadioButton defaultCompressionRadioButton;
    public JRadioButton customCompressionRadioButton;
    public JSpinner compressionLevel;
    public JTextPane compressionNoteText;

    public OptimizationPreferenesPane() {
        noCompresstionRadioButton.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                compressionLevel.setValue(0);
                compressionLevel.setEnabled(false);
                FileOptimizer.setPdfBoxCompression(0);
                compressionNoteText.setVisible(false);
            }
        });
        defaultCompressionRadioButton.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                compressionLevel.setValue(CompressParameters.DEFAULT_OBJECT_STREAM_SIZE);
                compressionLevel.setEnabled(false);
                FileOptimizer.setPdfBoxCompression(CompressParameters.DEFAULT_OBJECT_STREAM_SIZE);
                compressionNoteText.setVisible(true);
            }
        });
        customCompressionRadioButton.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                compressionLevel.setEnabled(true);
                compressionNoteText.setVisible(true);
            }
        });

        int currentCompression = FileOptimizer.getPdfBoxCompression();
        JComponent comp = compressionLevel.getEditor();
        JFormattedTextField field = (JFormattedTextField) comp.getComponent(0);
        DefaultFormatter formatter = (DefaultFormatter) field.getFormatter();
        formatter.setCommitsOnValidEdit(true);

        compressionLevel.setModel(new SpinnerNumberModel(currentCompression, 0.0, Integer.MAX_VALUE, 1.0));
        compressionLevel.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                storeCustomCompression();
                ;
            }
        });
        if (currentCompression == 0) {
            noCompresstionRadioButton.setSelected(true);
        } else if (currentCompression == CompressParameters.DEFAULT_OBJECT_STREAM_SIZE) {
            defaultCompressionRadioButton.setSelected(true);
        } else {
            customCompressionRadioButton.setSelected(true);
        }
    }

    protected void storeCustomCompression() {
        int c = -1;
        if (compressionLevel.getValue() instanceof Integer i) {
            c = i;
        }
        if (compressionLevel.getValue() instanceof Double i) {
            c = i.intValue();
        }
        if (compressionLevel.getValue() instanceof Float i) {
            c = i.intValue();
        }
        if (c >= 0) {
            FileOptimizer.setPdfBoxCompression(c);
        }

    }

    public void init(Preferences prefs) {
    }

    public void refresh() {
    }

    public void save(Preferences prefs) {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        topPanel = new JPanel();
        topPanel.setLayout(new GridLayoutManager(3, 2, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        topPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "PDFBox Compression", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        noCompresstionRadioButton = new JRadioButton();
        noCompresstionRadioButton.setText("No Compresstion");
        panel1.add(noCompresstionRadioButton, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        defaultCompressionRadioButton = new JRadioButton();
        defaultCompressionRadioButton.setText("Default");
        panel1.add(defaultCompressionRadioButton, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        customCompressionRadioButton = new JRadioButton();
        customCompressionRadioButton.setText("Custom");
        panel1.add(customCompressionRadioButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        compressionLevel = new JSpinner();
        compressionLevel.setToolTipText("0 - no compression, higher number has a chance of better compression but may slow down document display");
        panel1.add(compressionLevel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        compressionNoteText = new JTextPane();
        compressionNoteText.setEditable(false);
        compressionNoteText.setText("NOTE!\n\nWhen compression is enabled the  PDF document version will be forced to at least 1.6, as this is the minimum version that supports compresstion");
        topPanel.add(compressionNoteText, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final Spacer spacer1 = new Spacer();
        topPanel.add(spacer1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        topPanel.add(spacer2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(noCompresstionRadioButton);
        buttonGroup.add(defaultCompressionRadioButton);
        buttonGroup.add(customCompressionRadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topPanel;
    }

}
