package pmedit.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import pmedit.BatchOperationParameters;
import pmedit.CommandDescription;
import pmedit.MetadataInfo;
import pmedit.preset.PresetValues;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

public class BatchParametersExport extends BatchParametersWindow {
    private JPanel contentPane;
    private JButton buttonOK;
    public JButton btnSelectAll;
    public JButton selectNoneButton;
    public MetadataEditPane defaultMetadataPane;
    public JLabel hintLabel;
    public PresetSelector presetSelector;
    public JTextField outputFileName;
    public JPanel outputPane;
    public JCheckBox useRelativePaths;
    public JRadioButton perFileOutput;
    public JRadioButton singleFileOutput;
    public JLabel extensionLabel;

    public BatchParametersExport() {
        this(null, null, null);

    }

    public BatchParametersExport(BatchOperationParameters parameters, final Frame owner, CommandDescription command) {
        super(parameters, owner);
        setTitle("Batch Export parameters");
        setMinimumSize(new Dimension(640, 580));

        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(buttonOK);
        defaultMetadataPane.disableEdit();
        final MetadataInfo currentMetadata = parameters != null ? parameters.metadata.clone() : null;

        btnSelectAll.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (currentMetadata != null) {
                    currentMetadata.setEnabled(true);
                    defaultMetadataPane.fillEnabledFromMetadata(currentMetadata);
                }
            }
        });

        selectNoneButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (parameters != null) {
                    currentMetadata.setEnabled(false);
                    defaultMetadataPane.fillEnabledFromMetadata(currentMetadata);
                }
            }
        });

        buttonOK.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                windowClosed();

            }
        });

        defaultMetadataPane.showEnabled(true);
        defaultMetadataPane.fillFromMetadata(currentMetadata);

        presetSelector.addActionListener(e -> {
            if (e.getSource() instanceof PresetSelector.PresetActionData actionData) {
                if (actionData.isOnLoad()) {
                    PresetValues values = actionData.getPresetValues();
                    values.metadataEnabled = null;
                    defaultMetadataPane.onLoadPreset(values);
                } else if (actionData.isOnSave()) {
                    defaultMetadataPane.onSavePreset(actionData.getPresetValues());
                }
            }
        });

        singleFileOutput.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                outputFileName.setEnabled(e.getStateChange() == ItemEvent.SELECTED);
            }
        });

        outputFileName.setText(parameters.outputFile);


        useRelativePaths.setSelected(parameters.shouldUseRelativePaths());

        if (parameters.perFileExport != null) {
            perFileOutput.setSelected(parameters.perFileExport);
            singleFileOutput.setSelected(!parameters.perFileExport);
        } else {
            singleFileOutput.setSelected(true);
        }
        outputFileName.setEnabled(singleFileOutput.isSelected());


        if (command != null && command.name.startsWith("to")) {
            extensionLabel.setText("." + command.name.substring(2));
        } else {
            extensionLabel.setText(".???");

        }
    }

    protected void setMessage(String message) {
        hintLabel.setText(message);
    }

    public void windowClosed() {
        defaultMetadataPane.copyToMetadata(parameters.metadata);
        parameters.outputFile = outputFileName.getText();
        parameters.useRelativePaths = useRelativePaths.isSelected();
        parameters.perFileExport = perFileOutput.isSelected();
        super.windowClosed();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(4, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        buttonOK = new JButton();
        buttonOK.setText("Close");
        panel2.add(buttonOK, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(2, 4, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel3, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        hintLabel = new JLabel();
        hintLabel.setText("The selected fields below will be set in all files");
        panel3.add(hintLabel, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnSelectAll = new JButton();
        btnSelectAll.setText("Select all");
        panel3.add(btnSelectAll, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        selectNoneButton = new JButton();
        selectNoneButton.setText("Select none");
        panel3.add(selectNoneButton, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        defaultMetadataPane = new MetadataEditPane();
        panel3.add(defaultMetadataPane.$$$getRootComponent$$$(), new GridConstraints(1, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        presetSelector = new PresetSelector();
        contentPane.add(presetSelector.$$$getRootComponent$$$(), new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        outputPane = new JPanel();
        outputPane.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(outputPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        outputPane.setBorder(BorderFactory.createTitledBorder(null, "Output", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JLabel label1 = new JLabel();
        label1.setText("Filename");
        outputPane.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        outputFileName = new JTextField();
        outputPane.add(outputFileName, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        useRelativePaths = new JCheckBox();
        useRelativePaths.setText("Use relative paths in output");
        useRelativePaths.setToolTipText("This will make the file.fullPath field to be relative to the input file/dir instead of being absolute path");
        outputPane.add(useRelativePaths, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        outputPane.add(panel4, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        perFileOutput = new JRadioButton();
        perFileOutput.setText("Separate file for each input file");
        panel4.add(perFileOutput, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel4.add(spacer2, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        singleFileOutput = new JRadioButton();
        singleFileOutput.setText("Single output file");
        panel4.add(singleFileOutput, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        extensionLabel = new JLabel();
        extensionLabel.setText(".ext");
        outputPane.add(extensionLabel, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(perFileOutput);
        buttonGroup.add(singleFileOutput);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
