package pmedit.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import pmedit.BatchOperationParameters;
import pmedit.CommandLine;
import pmedit.MetadataInfo;
import pmedit.TemplateString;
import pmedit.prefs.Preferences;
import pmedit.ui.components.TextPaneWithLinks;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class BatchParametersExtract extends BatchParametersWindow {
    static final String HISTORY_KEY = "ExtractTemplate";
    private JPanel contentPane;
    private JButton buttonOK;
    public JComboBox extractTemplateCombo;
    public JTextField testFileName;
    public TextPaneWithLinks previewText;
    public JScrollPane previewScroll;
    public RenameTemplateOptions renameTemplateOptions;

    public String extractTemplate;


    public BatchParametersExtract() {
        this(null, null);
    }

    public BatchParametersExtract(BatchOperationParameters parameters, final Frame owner) {
        super(parameters, owner);
        setContentPane(contentPane);
        setModal(true);
        setTitle("Batch Extract parameters");

        extractTemplate = Preferences.getInstance().get("extractTemplate", null);
        String testString = Preferences.getInstance().get("extractTestString", null);
        if (testString != null) {
            testFileName.setText(testString);
        }

        String[] extractTemplateOptions = Preferences.getHistoryLines(HISTORY_KEY, new String[]{"", "{doc.author} - {doc.title}",
                "{doc.author} - {doc.subject}"});

        extractTemplateCombo.setModel(new DefaultComboBoxModel<String>(extractTemplateOptions));
        extractTemplateCombo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                extractTemplate = (String) extractTemplateCombo.getModel().getSelectedItem();
                if (showPreview(extractTemplate)) {
                    Preferences.appendHistoryLines(HISTORY_KEY, new String[]{extractTemplate});
                    Preferences.getInstance().put("extractTemplate", extractTemplate);
                    Preferences.getInstance().put("extractTestString", testFileName.getText());
                }
                ;
            }
        });
        if (extractTemplate != null && !extractTemplate.isEmpty()) {
            extractTemplateCombo.setSelectedItem(extractTemplate);
        }

        if (extractTemplateCombo.getEditor().getEditorComponent() instanceof JTextField tf) {
            new TextFieldContextMenu(tf).createContextMenu().addTemplatePlaceholders();
        }

        showPreview(extractTemplate);


        buttonOK.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                windowClosed();
            }
        });
    }

    public boolean showPreview(String template) {
        String messageTitle = "Available Fields:";
        String message = CommandLine.mdFieldsHelpMessage(60, "  {", "}", false);
        boolean isEmpty = true;
        if (template != null && !template.isEmpty()) {
            MetadataInfo md = new TemplateString(template).extract(testFileName.getText());
            isEmpty = md.isEmpty();
            if (!isEmpty) {
                messageTitle = "Matched:";
                message = new TemplateString(message).process(md, (e, v) -> {
                    if (v.isEmpty() || e.name() == null) {
                        return v;
                    }
                    return e.name() + "=<b style='color:green'>" + v + "</b>";
                }).stripTrailing();
            } else {
                messageTitle = "No match!";
                message = "<span style='color:red'>The extract template doesn't match the provided test file name </span>";
            }
        }
        previewText.setText("<b>" + messageTitle + "</b><br>\n<pre>\n<i>" + message + "</i></pre>");
        previewText.setSelectionStart(0);
        previewText.setSelectionEnd(0);
        return !isEmpty;
    }

    public void windowClosed() {
        parameters.extractTemplate = extractTemplate;
        super.windowClosed();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        buttonOK = new JButton();
        buttonOK.setText("Close");
        panel2.add(buttonOK, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(4, 5, new Insets(5, 5, 5, 5), -1, -1));
        contentPane.add(panel3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel3.setBorder(BorderFactory.createTitledBorder(null, "Extract Template", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        extractTemplateCombo = new JComboBox();
        extractTemplateCombo.setEditable(true);
        panel3.add(extractTemplateCombo, new GridConstraints(0, 0, 1, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Test File Name");
        panel3.add(label1, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        testFileName = new JTextField();
        panel3.add(testFileName, new GridConstraints(2, 2, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText(".pdf");
        panel3.add(label2, new GridConstraints(2, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, Font.ITALIC, -1, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setText("Select existing or enter new template and press Enter to preview");
        panel3.add(label3, new GridConstraints(1, 0, 1, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        previewScroll = new JScrollPane();
        panel3.add(previewScroll, new GridConstraints(3, 0, 1, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        previewText = new TextPaneWithLinks();
        previewScroll.setViewportView(previewText);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
