package pmedit.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import pmedit.MetadataInfo;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.beans.PropertyChangeEvent;

public class EncryptionOptionsDialog extends JDialog {
    private JPanel contentPane;
    private JButton buttonOK;
    public JPasswordField ownerPasswordTextField;
    public JPasswordField usePasswordTextField;
    public JButton showOwnerPassword;
    public JButton showUserPassword;
    char echoChar;
    MetadataInfo metadataInfo;

    public EncryptionOptionsDialog(Frame owner) {
        super(owner, true);
        setLocationRelativeTo(owner);
        setTitle("Encryption Options");

        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(buttonOK);

        buttonOK.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onOK();
            }
        });

        // call onCancel() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onOK();
            }
        });

        // call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onOK();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);

        pack();
        echoChar = ownerPasswordTextField.getEchoChar();
        showOwnerPassword.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ownerPasswordTextField.setEchoChar(
                        ownerPasswordTextField.getEchoChar() == 0 ? echoChar : (char) 0
                );
            }
        });
        showUserPassword.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                usePasswordTextField.setEchoChar(
                        usePasswordTextField.getEchoChar() == 0 ? echoChar : (char) 0
                );
            }
        });
    }

    public void display(MetadataInfo md) {
        metadataInfo = md;
        metadataInfo.getPropertyChangeSupport().addPropertyChangeListener(evt -> {
            if (evt.getSource() == this) {
                return;
            }
            if (evt.getPropertyName().equals("prop.ownerPassword") || evt.getPropertyName().equals("prop.userPassword")) {
                fill();
            }
        });

        fill();
        setVisible(true);
    }

    protected void fill() {

        if (metadataInfo != null) {
            if (metadataInfo.prop.ownerPassword != null) {
                ownerPasswordTextField.setText(metadataInfo.prop.ownerPassword);
            } else {
                ownerPasswordTextField.setText("");
            }
            if (metadataInfo.prop.userPassword != null) {
                usePasswordTextField.setText(metadataInfo.prop.userPassword);
            } else {
                usePasswordTextField.setText("");
            }
        }
    }

    public void notifyPropertyChanges() {
        if (metadataInfo != null) {
            String newOwnerPass = ownerPasswordTextField.getText();
            if (!newOwnerPass.equals(metadataInfo.prop.ownerPassword)) {
                String old = metadataInfo.prop.ownerPassword;
                metadataInfo.prop.ownerPassword = newOwnerPass;
                firePropertyChange("prop.ownerPassword", old, newOwnerPass);
            }
            String newUserPass = usePasswordTextField.getText();
            if (!newUserPass.equals(metadataInfo.prop.userPassword)) {
                String old = metadataInfo.prop.userPassword;
                metadataInfo.prop.userPassword = usePasswordTextField.getText();
                firePropertyChange("prop.userPassword", old, newUserPass);
            }
        }
    }

    protected void firePropertyChange(String propertyName, Object old, Object newV) {
        if (metadataInfo != null) {
            PropertyChangeEvent e = new PropertyChangeEvent(this, propertyName, old, newV);
            metadataInfo.getPropertyChangeSupport().firePropertyChange(e);
        }
    }


    private void onOK() {
        notifyPropertyChanges();
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        buttonOK = new JButton();
        buttonOK.setText("OK");
        panel2.add(buttonOK, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.add(panel3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Owner Password");
        panel3.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ownerPasswordTextField = new JPasswordField();
        panel3.add(ownerPasswordTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("User Password");
        panel3.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        usePasswordTextField = new JPasswordField();
        panel3.add(usePasswordTextField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        showOwnerPassword = new JButton();
        showOwnerPassword.setBorderPainted(false);
        showOwnerPassword.setContentAreaFilled(false);
        showOwnerPassword.setFocusPainted(false);
        showOwnerPassword.setIcon(new ImageIcon(getClass().getResource("/pmedit/ui/square-asterisk.png")));
        showOwnerPassword.setText("");
        panel3.add(showOwnerPassword, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        showUserPassword = new JButton();
        showUserPassword.setBorderPainted(false);
        showUserPassword.setContentAreaFilled(false);
        showUserPassword.setFocusPainted(false);
        showUserPassword.setIcon(new ImageIcon(getClass().getResource("/pmedit/ui/square-asterisk.png")));
        showUserPassword.setText("");
        panel3.add(showUserPassword, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
