package pmedit.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import pmedit.ext.PmeExtension;
import pmedit.ui.ext.PreferencesWindowInterface;
import pmedit.ui.preferences.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.prefs.Preferences;

public class PreferencesWindow extends JDialog implements PreferencesWindowInterface {
    public JPanel contentPane;
    public JTabbedPane tabbedPane;
    public JButton closeButton;
    public DefaultsPreferences defaultMetadataForm;
    public GeneralPreferences generalPreferencesForm;
    public OptimizationPreferenesPane optimizationPreferencesForm;
    public LicensePreferences licenseForm;
    public LookAndFeelPreferences lookAndFeelForm;

    final Preferences prefs = pmedit.prefs.Preferences.getInstance();
    Runnable onSave;
    private PmeExtension extension = PmeExtension.get();

    public PreferencesWindow() {
        this(null);
    }

    public PreferencesWindow(final Frame owner) {
        super(owner, "Preferences", ModalityType.APPLICATION_MODAL);
        super.setLocationRelativeTo(owner);
        setContentPane(contentPane);
        setModal(true);
        setMinimumSize(new Dimension(860, 600));
        contentPane.doLayout();

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent arg0) {
                save();
            }
        });
        closeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
                save();
            }
        });

        init();
        refresh();
    }

    public void init() {
        generalPreferencesForm.init(prefs);
        defaultMetadataForm.init(prefs);
        optimizationPreferencesForm.init(prefs);
        licenseForm.init(prefs);
        lookAndFeelForm.init(prefs);
        extension.initPreferencesTabs(this);
    }

    public void save() {
        generalPreferencesForm.save(prefs);
        defaultMetadataForm.save(prefs);
        optimizationPreferencesForm.save(prefs);
        licenseForm.save(prefs);
        lookAndFeelForm.save(prefs);

        if (onSave != null)
            onSave.run();
    }

    public void refresh() {
        generalPreferencesForm.refresh();
        defaultMetadataForm.refresh();
        optimizationPreferencesForm.refresh();
        licenseForm.refresh();
        licenseForm.refresh();
        extension.onPreferencesRefresh(this);
    }

    public void showTab(String tabName) {
        int idx = tabName == null || tabName.isEmpty() ? 0 : tabbedPane.indexOfTab(tabName);
        if (idx >= 0) {
            tabbedPane.setSelectedIndex(idx);
        }
    }

    public void onSaveAction(Runnable newAction) {
        onSave = newAction;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane = new JTabbedPane();
        contentPane.add(tabbedPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(300, 300), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 3, 0), -1, -1));
        tabbedPane.addTab("General", panel1);
        generalPreferencesForm = new GeneralPreferences();
        panel1.add(generalPreferencesForm.$$$getRootComponent$$$(), new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane.addTab("Defaults", panel2);
        defaultMetadataForm = new DefaultsPreferences();
        panel2.add(defaultMetadataForm.$$$getRootComponent$$$(), new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane.addTab("Compression", panel3);
        optimizationPreferencesForm = new OptimizationPreferenesPane();
        panel3.add(optimizationPreferencesForm.$$$getRootComponent$$$(), new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane.addTab("License", panel4);
        licenseForm = new LicensePreferences();
        panel4.add(licenseForm.$$$getRootComponent$$$(), new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane.addTab("Look & Feel", panel5);
        lookAndFeelForm = new LookAndFeelPreferences();
        panel5.add(lookAndFeelForm.$$$getRootComponent$$$(), new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane.addTab("About", panel6);
        final AboutPreferences nestedForm1 = new AboutPreferences();
        panel6.add(nestedForm1.$$$getRootComponent$$$(), new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 3, 3), -1, -1));
        contentPane.add(panel7, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        closeButton = new JButton();
        closeButton.setEnabled(true);
        closeButton.setText("Close");
        panel7.add(closeButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel7.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
