package pmedit.ui.preferences;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import pmedit.ui.RenameTemplateOptions;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.prefs.Preferences;

public class GeneralPreferences {
    public JRadioButton rdbtnSave;
    public JRadioButton rdbtnSaveAndRename;
    public JRadioButton rdbtnSaveAs;
    public JPanel topPanel;
    public RenameTemplateOptions renameTemplateOptions;

    public String defaultSaveAction;


    public GeneralPreferences() {
        Preferences prefs = pmedit.prefs.Preferences.getInstance();

        // Default save action
        ActionListener onDefaultSaveAction = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (rdbtnSave.isSelected()) {
                    defaultSaveAction = "save";
                } else if (rdbtnSaveAndRename.isSelected()) {
                    defaultSaveAction = "saveRename";

                } else if (rdbtnSaveAs.isSelected()) {
                    defaultSaveAction = "saveAs";
                }
            }
        };
        rdbtnSave.addActionListener(onDefaultSaveAction);
        rdbtnSaveAndRename.addActionListener(onDefaultSaveAction);
        rdbtnSaveAs.addActionListener(onDefaultSaveAction);
        defaultSaveAction = prefs.get("defaultSaveAction", "save");
        if (defaultSaveAction.equals("saveRename")) {
            rdbtnSaveAndRename.setSelected(true);
        } else if (defaultSaveAction.equals("saveAs")) {
            rdbtnSaveAndRename.setSelected(true);
        } else {
            rdbtnSave.setSelected(true);
        }

    }

    public void init(Preferences prefs) {
        // Rename template
        renameTemplateOptions.init();
    }

    public void refresh() {

        renameTemplateOptions.refresh();
    }

    public void save(Preferences prefs) {

        prefs.put("defaultSaveAction", defaultSaveAction);

        renameTemplateOptions.save(prefs);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        topPanel = new JPanel();
        topPanel.setLayout(new GridLayoutManager(2, 4, new Insets(10, 10, 10, 10), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        topPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "Default Save Action", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        rdbtnSave = new JRadioButton();
        rdbtnSave.setText("Save");
        panel1.add(rdbtnSave, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        rdbtnSaveAndRename = new JRadioButton();
        rdbtnSaveAndRename.setText("Save and Rename");
        panel1.add(rdbtnSaveAndRename, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rdbtnSaveAs = new JRadioButton();
        rdbtnSaveAs.setText("Save as ...");
        panel1.add(rdbtnSaveAs, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        renameTemplateOptions = new RenameTemplateOptions();
        topPanel.add(renameTemplateOptions.$$$getRootComponent$$$(), new GridConstraints(1, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(rdbtnSave);
        buttonGroup.add(rdbtnSaveAndRename);
        buttonGroup.add(rdbtnSaveAs);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topPanel;
    }

}
