package pmedit.ui.preferences;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.jetbrains.annotations.NotNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import pmedit.WindowsRegisterContextMenu;
import pmedit.prefs.GuiPreferences;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;
import java.util.prefs.Preferences;

public class LookAndFeelPreferences {
    public JComboBox lookAndFeelSelection;
    public JPanel topPanel;
    public JButton registerContextMenu;
    public JButton unregisterContextMenu;

    public record LaF(String name, String className) {
        public @NotNull String toString() {
            return name;
        }
    }

    protected static LaF[] lafListCached = null;

    public static LaF[] lafList() {
        if (lafListCached == null) {
            UIManager.LookAndFeelInfo[] lafInfos = UIManager.getInstalledLookAndFeels();
            final int numFlat = 4;
            LaF[] laf = new LaF[lafInfos.length + numFlat];

            laf[0] = new LaF("Flat Light", FlatLightLaf.class.getName());
            laf[1] = new LaF("Flat Dark", FlatDarkLaf.class.getName());
            laf[2] = new LaF("Flat IntelliJ", FlatIntelliJLaf.class.getName());
            laf[3] = new LaF("Flat Darcula", FlatDarculaLaf.class.getName());

            for (int i = 0; i < lafInfos.length; i++) {
                laf[i + numFlat] = new LaF(lafInfos[i].getName(), lafInfos[i].getClassName());
            }
            lafListCached = laf;
        }
        return lafListCached;
    }

    public LookAndFeelPreferences() {
        lookAndFeelSelection.setModel(new DefaultComboBoxModel(lafList()));

        registerContextMenu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    WindowsRegisterContextMenu.register();
                } catch (Exception ex) {
                    Logger LOG = LoggerFactory.getLogger(LookAndFeelPreferences.class);
                    LOG.error("Failed to register context menu!", ex);
                    JOptionPane.showMessageDialog(
                            SwingUtilities.getWindowAncestor(topPanel),
                            "Failed to register context menu:\n" + e,
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }
        });
        unregisterContextMenu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    WindowsRegisterContextMenu.unregister();
                } catch (Exception ex) {
                    Logger LOG = LoggerFactory.getLogger(LookAndFeelPreferences.class);
                    LOG.error("Failed to register context menu!", ex);
                    JOptionPane.showMessageDialog(
                            SwingUtilities.getWindowAncestor(topPanel),
                            "Failed to register context menu:\n" + e,
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }
        });
    }


    public void init(Preferences prefs) {
        String c = GuiPreferences.getLookAndFeelClass();
        if (c != null) {
            DefaultComboBoxModel<LaF> m = (DefaultComboBoxModel<LaF>) lookAndFeelSelection.getModel();
            for (int i = 0; i < m.getSize(); i++) {
                if (m.getElementAt(i).className.equals(c)) {
                    m.setSelectedItem(m.getElementAt(i));
                }
            }
        }
    }

    public void refresh() {

    }

    public void save(Preferences prefs) {
        LaF current = (LaF) lookAndFeelSelection.getModel().getSelectedItem();
        if (current == null) {
            return;
        }
        GuiPreferences.setLookAndFeelClass(current.className);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        topPanel = new JPanel();
        topPanel.setLayout(new GridLayoutManager(6, 2, new Insets(10, 10, 10, 10), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Select Look And Feel");
        topPanel.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        topPanel.add(spacer1, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        lookAndFeelSelection = new JComboBox();
        topPanel.add(lookAndFeelSelection, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        topPanel.add(spacer2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$(null, Font.ITALIC, -1, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setText("Restart is required for this option to take effect");
        topPanel.add(label2, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        topPanel.add(panel1, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel1.setBorder(BorderFactory.createTitledBorder(null, "Context Menu Integration", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        registerContextMenu = new JButton();
        registerContextMenu.setText("Install");
        panel1.add(registerContextMenu, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        panel1.add(spacer3, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        unregisterContextMenu = new JButton();
        unregisterContextMenu.setText("Remove");
        panel1.add(unregisterContextMenu, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        topPanel.add(spacer4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topPanel;
    }

}
