package pmedit.ui.preferences;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.apache.pdfbox.pdfwriter.compress.CompressParameters;
import pmedit.FileOptimizer;
import pmedit.WebsiteConstants;
import pmedit.ext.BasicPdfWriter;
import pmedit.ui.components.TextPaneWithLinks;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.text.DefaultFormatter;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.prefs.Preferences;

public class OptimizationPreferenesPane {

    public JPanel topPanel;
    public JRadioButton noCompresstionRadioButton;
    public JRadioButton defaultCompressionRadioButton;
    public JRadioButton customCompressionRadioButton;
    public JSpinner compressionLevel;
    public JLabel compressionMinVersion;
    public JComboBox<Integer> defaultEncryptionKeyLength;
    public JCheckBox preferAes;
    public TextPaneWithLinks compressionHelpLink;

    public OptimizationPreferenesPane() {
        noCompresstionRadioButton.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                compressionLevel.setValue(0);
                compressionLevel.setEnabled(false);
                FileOptimizer.setPdfBoxCompression(0);
            }
        });
        defaultCompressionRadioButton.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                compressionLevel.setValue((double) CompressParameters.DEFAULT_OBJECT_STREAM_SIZE);
                compressionLevel.setEnabled(false);
                FileOptimizer.setPdfBoxCompression(CompressParameters.DEFAULT_OBJECT_STREAM_SIZE);
            }
        });
        customCompressionRadioButton.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                compressionLevel.setEnabled(true);
            }
        });

        int currentCompression = FileOptimizer.getPdfBoxCompression();
        JComponent comp = compressionLevel.getEditor();
        JFormattedTextField field = (JFormattedTextField) comp.getComponent(0);
        DefaultFormatter formatter = (DefaultFormatter) field.getFormatter();
        formatter.setCommitsOnValidEdit(true);

        compressionLevel.setModel(new SpinnerNumberModel(currentCompression, 0.0, Integer.MAX_VALUE, 1.0));
        compressionLevel.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                storeCustomCompression();
                ;
            }
        });
        compressionHelpLink.setText(WebsiteConstants.getLink(WebsiteConstants.pdfCompressionHelp, "Compression Parameter Explanation"));
        if (currentCompression == 0) {
            noCompresstionRadioButton.setSelected(true);
        } else if (currentCompression == CompressParameters.DEFAULT_OBJECT_STREAM_SIZE) {
            defaultCompressionRadioButton.setSelected(true);
        } else {
            customCompressionRadioButton.setSelected(true);
        }
        compressionMinVersion.setText(String.valueOf(new BasicPdfWriter().getCompressionMinimumSupportedVersion()));
        defaultEncryptionKeyLength.setModel(new DefaultComboBoxModel<Integer>(FileOptimizer.ALLOWED_KEY_LENGTHS));
        defaultEncryptionKeyLength.addItemListener(e -> FileOptimizer.setEncryptionKeyLength((Integer) e.getItem()));

        preferAes.setSelected(FileOptimizer.getPreferAes());
        preferAes.addChangeListener(e -> FileOptimizer.setPreferAes(preferAes.isSelected()));
    }

    protected void storeCustomCompression() {
        int c = -1;
        if (compressionLevel.getValue() instanceof Integer i) {
            c = i;
        }
        if (compressionLevel.getValue() instanceof Double i) {
            c = i.intValue();
        }
        if (compressionLevel.getValue() instanceof Float i) {
            c = i.intValue();
        }
        if (c >= 0) {
            FileOptimizer.setPdfBoxCompression(c);
        }

    }

    public void init(Preferences prefs) {
    }

    public void refresh() {
    }

    public void save(Preferences prefs) {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        topPanel = new JPanel();
        topPanel.setLayout(new GridLayoutManager(6, 2, new Insets(10, 10, 10, 10), -1, -1));
        final Spacer spacer1 = new Spacer();
        topPanel.add(spacer1, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Minimum PDF Version Supporting Compression");
        topPanel.add(label1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        compressionMinVersion = new JLabel();
        compressionMinVersion.setText("n/a");
        topPanel.add(compressionMinVersion, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Default Encryption Key Length");
        topPanel.add(label2, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        defaultEncryptionKeyLength = new JComboBox();
        topPanel.add(defaultEncryptionKeyLength, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Preffer AES (when 128 bit key)");
        topPanel.add(label3, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        preferAes = new JCheckBox();
        preferAes.setText("");
        topPanel.add(preferAes, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        topPanel.add(panel1, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(4, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "PDFBox Compression", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        noCompresstionRadioButton = new JRadioButton();
        noCompresstionRadioButton.setText("No Compresstion");
        panel2.add(noCompresstionRadioButton, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        defaultCompressionRadioButton = new JRadioButton();
        defaultCompressionRadioButton.setText("Default");
        panel2.add(defaultCompressionRadioButton, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        customCompressionRadioButton = new JRadioButton();
        customCompressionRadioButton.setText("Custom");
        panel2.add(customCompressionRadioButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        compressionLevel = new JSpinner();
        compressionLevel.setToolTipText("0 - no compression, higher number has a chance of better compression but may slow down document display");
        panel2.add(compressionLevel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        compressionHelpLink = new TextPaneWithLinks();
        compressionHelpLink.setEnabled(true);
        panel2.add(compressionHelpLink, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, 1, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel1.add(spacer2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        panel1.add(spacer3, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        topPanel.add(spacer4, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, 1, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 20), new Dimension(-1, 20), new Dimension(-1, 20), 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(noCompresstionRadioButton);
        buttonGroup.add(defaultCompressionRadioButton);
        buttonGroup.add(customCompressionRadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topPanel;
    }

}
