package pmedit;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.plaf.basic.BasicArrowButton;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.util.Arrays;
import java.util.stream.Collectors;

public class ActionsAndOptions {
    public JPanel topPanel;
    public JButton copyXMPToDocumentButton;
    public JButton copyDocumentToXMPButton;
    public JCheckBox removeDocumentCheckBox;
    public JCheckBox removeXMPCheckBox;
    public JButton btnSave;
    public BasicArrowButton btnSaveMenu;
    public JComboBox<Float> pdfVersion;
    public JButton encryptionButton;
    public JCheckBox enableEncryption;
    public EncryptionOptionsDialog encryptionOptionsDialog;
    public EncryptionOptions encryptionOptions;

    void createUIComponents() {
        btnSaveMenu = new BasicArrowButton(BasicArrowButton.SOUTH);
    }

    public ActionsAndOptions() {
        $$$setupUI$$$();
        btnSave.setIcon(new ImageIcon(
                PDFMetadataEditWindow.class
                        .getResource("save-icon.png")));

        pdfVersion.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Component renderer = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                if (value instanceof Double) {
                    // Format the double value to round it to 2 decimal places
                    DecimalFormat df = new DecimalFormat("#.##");
                    setText(df.format((Double) value));
                }

                return renderer;
            }
        });

        encryptionOptionsDialog = new EncryptionOptionsDialog((JFrame) SwingUtilities.windowForComponent(topPanel));
        encryptionButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                encryptionOptionsDialog.display(encryptionOptions);
            }
        });
        encryptionButton.setEnabled(encryptionOptions != null);
        enableEncryption.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                encryptionOptions.hasEncryption = enableEncryption.isSelected();
                encryptionButton.setEnabled(encryptionOptions.hasEncryption);
            }
        });
    }

    static double[] versions = new double[]{1.4f, 1.5f, 1.6f, 1.7f};

    public void setCurrentDocumentVersion(float version) {
        var model = new DefaultComboBoxModel<Float>() {

        };
        model.addAll(Arrays.stream(versions).filter(e -> e >= version).boxed().map(Double::floatValue).collect(Collectors.toList()));
        pdfVersion.setModel(model);
        model.setSelectedItem(version);
    }

    public void setDocumentProtection(EncryptionOptions options) {
        encryptionOptions = options;
        encryptionOptionsDialog.options = encryptionOptions;
        encryptionButton.setEnabled(encryptionOptions.hasEncryption);
        enableEncryption.setSelected(encryptionOptions.hasEncryption);
    }

    public EncryptionOptions getDocumentProtection() {
        return encryptionOptionsDialog.getCurrentOptions();
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        topPanel = new JPanel();
        topPanel.setLayout(new GridLayoutManager(4, 4, new Insets(0, 0, 0, 0), -1, -1));
        copyXMPToDocumentButton = new JButton();
        copyXMPToDocumentButton.setText("Copy XMP to Document");
        topPanel.add(copyXMPToDocumentButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        topPanel.add(spacer1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        copyDocumentToXMPButton = new JButton();
        copyDocumentToXMPButton.setText("Copy Document to XMP");
        topPanel.add(copyDocumentToXMPButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        removeDocumentCheckBox = new JCheckBox();
        removeDocumentCheckBox.setText("Remove Document");
        topPanel.add(removeDocumentCheckBox, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        removeXMPCheckBox = new JCheckBox();
        removeXMPCheckBox.setText("Remove XMP");
        topPanel.add(removeXMPCheckBox, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Copy Metadata ");
        topPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("On save");
        topPanel.add(label2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        topPanel.add(panel1, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("as PDF Version");
        panel1.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pdfVersion = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("1.4");
        defaultComboBoxModel1.addElement("1.5");
        defaultComboBoxModel1.addElement("1.6");
        defaultComboBoxModel1.addElement("1.7");
        pdfVersion.setModel(defaultComboBoxModel1);
        panel1.add(pdfVersion, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), 0, -1));
        topPanel.add(panel2, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        btnSave = new JButton();
        btnSave.setText("Save");
        panel2.add(btnSave, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnSaveMenu.setText("");
        panel2.add(btnSaveMenu, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        topPanel.add(panel3, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        encryptionButton = new JButton();
        encryptionButton.setText("Encryption");
        panel3.add(encryptionButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        enableEncryption = new JCheckBox();
        enableEncryption.setHideActionText(true);
        enableEncryption.setText("");
        panel3.add(enableEncryption, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topPanel;
    }

}
