#!/bin/bash

THIS_DIR=$(cd "$(dirname "$0")"; pwd)
JAR_FILE='${project.build.finalName}.jar'
if [ ! -f "$THIS_DIR/$JAR_FILE" ]; then
	JAR_FILE=$(cd "$THIS_DIR"; for i in pdf-metadata-edit*.jar; do [ -e $i ] && echo $i; done | sort -r -g | head -n1)
fi

exec java -DnoGui -jar "$THIS_DIR/$JAR_FILE" "$@"
