package pmedit.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import pmedit.CommandLine;
import pmedit.MetadataInfo;
import pmedit.TemplateString;
import pmedit.prefs.Preferences;
import pmedit.ui.components.TextPaneWithLinks;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.JTextComponent;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;
import java.util.function.Function;
import java.util.function.Supplier;

public class RenameTemplateOptions {
    public static final String RENAME_TEMPLATE_KEY = "renameTemplate";
    private JPanel contentPane;
    public JComboBox<String> renameTemplateComboBox;
    public JLabel previewLabel;
    public TextPaneWithLinks supportedFieldsHelp;

    public String renameTemplate;
    protected String preferencesKey = RENAME_TEMPLATE_KEY;

    public RenameTemplateOptions() {
    }

    public void init() {
        init(RENAME_TEMPLATE_KEY,  () -> Preferences.getInstance().get(RENAME_TEMPLATE_KEY, null));
    }

    public void init(String name, Supplier<String> initialOption) {
        preferencesKey = name;
        renameTemplate = initialOption.get();


        String[] renameTemplateOptions = Preferences.getHistoryLines(preferencesKey, new String[]{"", "{doc.author} - {doc.title}.pdf",
                "{doc.author} - {doc.creationDate}.pdf"});
        renameTemplateComboBox.setModel(new DefaultComboBoxModel<String>(renameTemplateOptions));
        final JTextComponent tcA = (JTextComponent) renameTemplateComboBox.getEditor().getEditorComponent();
        renameTemplateComboBox.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                if (showPreview((String) renameTemplateComboBox.getModel().getSelectedItem())) {
                    Preferences.appendHistoryLines(preferencesKey, new String[]{renameTemplate});
                }
                ;
            }
        });

        if (renameTemplateComboBox.getEditor().getEditorComponent() instanceof JTextField tf) {
            new TextFieldContextMenu(tf).createContextMenu().addTemplatePlaceholders();
        }

        supportedFieldsHelp.setText("Supported fields:<br>\n<pre>\n<i>" + CommandLine.mdFieldsHelpMessage(60, "  {", "}", false) + "</i></pre>");

        refresh();
    }

    public boolean showPreview(String template) {
        renameTemplate = template;
        TemplateString ts = new TemplateString(template);
        String previewString = ts.process(MetadataInfo.getSampleMetadata());

        previewLabel.setText(previewString);
        return !previewString.equals(template);
    }

    public void refresh() {
        renameTemplateComboBox.setSelectedItem(renameTemplate);
        showPreview(renameTemplate);
    }

    public void save(java.util.prefs.Preferences prefs) {
        if (renameTemplate != null && !renameTemplate.isEmpty())
            prefs.put(preferencesKey, renameTemplate);
        else
            prefs.remove(preferencesKey);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 1, new Insets(5, 5, 5, 5), -1, 5));
        contentPane.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), "Rename template", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        renameTemplateComboBox = new JComboBox();
        renameTemplateComboBox.setEditable(true);
        panel1.add(renameTemplateComboBox, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, Font.ITALIC, -1, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Select existing or enter new template and press Enter to preview");
        panel1.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        panel2.setBorder(BorderFactory.createTitledBorder(null, "Preview", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        previewLabel = new JLabel();
        previewLabel.setText("");
        panel2.add(previewLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        supportedFieldsHelp = new TextPaneWithLinks();
        supportedFieldsHelp.setEditable(false);
        scrollPane1.setViewportView(supportedFieldsHelp);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }


}
